### ISSUE TITLE
How can I paginate response from favorite() ?

### ISSUE THREAD

**Issue by prince30** [ChristianKuri/laravel-favorite#5]

**Comment by vladshoob** [comment]
To anybody looking for a solution.

Favorite doing ->get() to Builder.

We need to build our own query in order to access Paginator:

`
auth()->user()->favorites()->where('favoriteable_type', SomeClass::class)->with('favoriteable')->paginate(10);
`

After this we should swap collection.

`
@php
    $collection = $objects->mapWithKeys(function ($item) {
        return [$item['favoriteable']->id=>$item['favoriteable']];
    })
@endphp
`
